name: build-test
on:
  push:
    branches:
      - "main"
      - "dev-v3"
      - "release-**"
  pull_request:
    branches:
      - "main"
      - "dev-v3"

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, monkci-runners-8vcpu]
    steps:
      - name: Clean workspace
        run: |
          chmod -R u+w ${{ github.workspace }} 2>/dev/null || true
          rm -rf ${{ github.workspace }}/* 2>/dev/null || true
        continue-on-error: true
        
      - name: Checkout source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # pin@v6.0.1
      - name: Add variables to environment file
        run: cat ".github/env" >> "$GITHUB_ENV"
      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # pin@6.1.0
        with:
          go-version: '${{ env.GOLANG_VERSION }}'
          check-latest: true
      - name: Test source headers are present
        run: make test-source-headers
      - name: Check if go modules need to be tidied
        run: go mod tidy -diff
      - name: Run unit tests
      
        run: make test-coverage
      - name: Test build
        run: make build
